let s="Asansol";
let p="Durgapur";
let q="Kolkata";
let k="5.1";
let n=8.1;
console.log(s);
console.log(s.length);
console.log(s.slice(0,2));
console.log(s.substring(0,5));
console.log(s.substr(0,5));
console.log(s.replace('A','D'));
console.log(s.replaceAll('s','D'));
console.log(s.toUpperCase());
console.log(s.toLowerCase());
console.log(s.concat(s));
console.log(s.search('l'));
console.log(s.concat(p.concat(q)));
console.log(s.trim());
console.log(s.padEnd(10,'x'));
//console.log(s.includes(0,'Asansol'));
console.log(n.toFixed());
console.log(n.valueOf());
console.log(Number(k));
console.log(parseInt(k));
console.log(parseFloat(k));
