let arr=[1,2,3,4,5,6];
let twoD=[[1,2],[3,4],[5,6]];
console.log(arr);
console.log(arr.length);
console.log(arr[0]);
console.log(arr.indexOf(5));
console.log(arr.push(7));
console.log(arr);
console.log(arr.pop());
console.log(arr.shift());
console.log(arr);
console.log(arr.push(8));
console.log(arr);
console.log(arr.unshift());
console.log(arr);
console.log(arr.push(7));
console.log(arr.toString());
console.log(arr.push(7));
console.log(arr.sort());
console.log(arr.reverse());
console.log(arr.push(7));
console.log(twoD.flat());
